export const isoAlpha2Countries = {
  AF: "Afeganistão",
  AX: "Ilhas Aland",
  AL: "Albânia",
  DZ: "Argélia",
  AS: "Samoa Americana",
  AD: "Andorra",
  AO: "Angola",
  AI: "Anguilla",
  AQ: "Antártida",
  AG: "Antígua And Barbuda",
  AR: "Argentina",
  AM: "Armênia",
  AW: "Aruba",
  AU: "Austrália",
  AT: "Áustria",
  AZ: "Azerbaijão",
  BS: "Bahamas",
  BH: "Bahrein",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Bélgica",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermudas",
  BT: "Butão",
  BO: "Bolívia",
  BA: "Bósnia-Herzegóvina",
  BW: "Botsuana",
  BV: "Ilha Bouvet",
  BR: "Brasil",
  IO: "Terr. Britânico do Oceano Índico",
  BN: "Brunei",
  BG: "Bulgária",
  BF: "Burkina Fasso",
  BI: "Burundi",
  KH: "Camboja",
  CM: "Camarões",
  CA: "Canadá",
  CV: "Cabo Verde",
  KY: "Ilhas Cayman",
  CF: "República Centro-Africana",
  TD: "Chade",
  CL: "Chile",
  CN: "China",
  CX: "Ilha Natal",
  CC: "Ilhas Cocos",
  CO: "Colômbia",
  KM: "Comoros",
  CG: "Congo",
  CD: "República Democrática do Congo",
  CK: "Ilhas Cook",
  CR: "Costa Rica",
  CI: "Costa do Marfim",
  HR: "Croácia",
  CU: "Cuba",
  CY: "Chipre",
  CZ: "República Tcheca",
  DK: "Dinamarca",
  DJ: "Djibuti",
  DM: "Dominica",
  DO: "República Dominicana",
  EC: "Equador",
  EG: "Egito",
  SV: "El Salvador",
  GQ: "Guiné Equatorial",
  ER: "Eritréia",
  EE: "Estônia",
  ET: "Etiópia",
  FK: "Ilhas Falkland (Malvinas)",
  FO: "Ilhas Faroes",
  FJ: "Fiji",
  FI: "Finlândia",
  FR: "França",
  GF: "Guiana Francesa",
  PF: "Polinésia Francesa",
  TF: "Territórios do Sul da França",
  GA: "Gabão",
  GM: "Gâmbia",
  GE: "Geórgia",
  DE: "Alemanha",
  GH: "Gana",
  GI: "Gibraltar",
  GR: "Grécia",
  GL: "Groelândia",
  GD: "Granada",
  GP: "Guadalupe",
  GU: "Guam",
  GT: "Guatemala",
  GG: "Guernsey",
  GN: "Guiné",
  GW: "Guiné-Bissau",
  GY: "Guiana",
  HT: "Haiti",
  HM: "Ilhas Heard e McDonald",
  VA: "Vaticano",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungria",
  IS: "Islândia",
  IN: "Índia",
  ID: "Indonésia",
  IR: "Irã",
  IQ: "Iraque",
  IE: "Irlanda",
  IM: "Ilha do Homem",
  IL: "Israel",
  IT: "Itália",
  JM: "Jamaica",
  JP: "Japão",
  JE: "Jersey",
  JO: "Jordânia",
  KZ: "Cazaquistão",
  KE: "Kênia",
  KI: "Kiribati",
  KR: "Coréia do Sul",
  KW: "Kuait",
  KG: "Quirguistão",
  LA: "Laos",
  LV: "Letônia",
  LB: "Líbano",
  LS: "Lesoto",
  LR: "Libéria",
  LY: "Líbia",
  LI: "Liechtenstein",
  LT: "Lituânia",
  LU: "Luxemburgo",
  MO: "Macau",
  MK: "Macedônia",
  MG: "Madagascar",
  MW: "Malaui",
  MY: "Malásia",
  MV: "Maldivas",
  ML: "Mali",
  MT: "Malta",
  MH: "Ilhas Marshall",
  MQ: "Martinica",
  MR: "Mauritânia",
  MU: "Maurício",
  YT: "Mayotte",
  MX: "México",
  FM: "Micronésia",
  MD: "Moldova",
  MC: "Mônaco",
  MN: "Mongólia",
  ME: "Montenegro",
  MS: "Montserrat",
  MA: "Marrocos",
  MZ: "Moçambique",
  MM: "Myamar",
  NA: "Namíbia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Holanda",
  AN: "Antilhas Holandesas",
  NC: "Nova Caledônia",
  NZ: "Nova Zelândia",
  NI: "Nicarágua",
  NE: "Níger",
  NG: "Nigéria",
  NU: "Niue",
  NF: "Ilhas Norfolk",
  MP: "Ilhas Marianas do Norte",
  NO: "Noruega",
  OM: "Omã",
  PK: "Paquistão",
  PW: "Palau",
  PS: "Palestina/Gaza",
  PA: "Panamá",
  PG: "Papua-Nova Guiné",
  PY: "Paraguai",
  PE: "Peru",
  PH: "Filipinas",
  PN: "Pitcairn",
  PL: "Polônia",
  PT: "Portugal",
  PR: "Porto Rico",
  QA: "Qatar",
  RE: "Ilhas Reunião",
  RO: "Romênia",
  RU: "Federação Russa",
  RW: "Ruanda",
  BL: "Santo Bartolomeu",
  SH: "Santa Helena",
  KN: "São Cristóvão e Névis (Kitts)",
  LC: "Santa Lúcia",
  MF: "São Martim",
  PM: "São Pedro e Miquelon",
  VC: "São Vincente e Granadinas",
  WS: "Samoa Ocidental",
  SM: "San Marino",
  ST: "São Tomé e Príncipe",
  SA: "Arábia Saudita",
  SN: "Senegal",
  RS: "Sérvia",
  SC: "Ilhas Seychelles",
  SL: "Serra Leoa",
  SG: "Cingapura",
  SK: "Eslováquia",
  SI: "Eslovênia",
  SB: "Ilhas Solomão",
  SO: "Somália",
  ZA: "South Africa",
  GS: "Ilhas Geórgia Sul e Sandwich Sul",
  ES: "Espanha",
  LK: "Sri Lanka",
  SD: "Sudão",
  SR: "Suriname",
  SJ: "Ilhas Svalbard e Jan Mayen",
  SZ: "Suazilânida",
  SE: "Suécia",
  CH: "Suíça",
  SY: "Síria",
  TW: "Taiwan",
  TJ: "Tajiquistão",
  TZ: "Tanzânia",
  TH: "Tailândia",
  TL: "Timor-Leste",
  TG: "Togo",
  TK: "Ilhas Tokelau",
  TO: "Tonga",
  TT: "Trinidade e Tobago",
  TN: "Tunísia",
  TR: "Turquia",
  TM: "Turcomenistão",
  TC: "Ilhas Turks e Caicos",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ucrânia",
  AE: "Emirados árabes Unidos",
  GB: "Reino Unido",
  US: "Estados Unidos",
  UM: "Ilhas Menores dos EUA",
  UY: "Uruguai",
  UZ: "Uzbequistão",
  VU: "Vanuatu",
  VE: "Venezuela",
  VN: "Vietnã",
  VG: "Ilhas Virgens (Inglaterra)",
  VI: "Ilhas Virgens (EUA)",
  WF: "Ilhas Wallis e Futuna",
  EH: "Saara Ocidental",
  YE: "Iêmen",
  ZM: "Zâmbia",
  ZW: "Zimbábue",
}

export const countries = [
  { alpha2: "AF", name: "Afeganistão", alpha3: "AFG", numeric: "004" },
  { alpha2: "AL", name: "Albânia", alpha3: "ALB", numeric: "008" },
  { alpha2: "DZ", name: "Argélia", alpha3: "DZA", numeric: "012" },
  { alpha2: "AS", name: "Samoa Americana", alpha3: "ASM", numeric: "016" },
  { alpha2: "AD", name: "Andorra", alpha3: "AND", numeric: "020" },
  { alpha2: "AO", name: "Angola", alpha3: "AGO", numeric: "024" },
  { alpha2: "AI", name: "Anguilla", alpha3: "AIA", numeric: "660" },
  { alpha2: "AQ", name: "Antártida", alpha3: "ATA", numeric: "010" },
  { alpha2: "AG", name: "Antígua and Barbuda", alpha3: "ATG", numeric: "028" },
  { alpha2: "AR", name: "Argentina", alpha3: "ARG", numeric: "032" },
  { alpha2: "AM", name: "Armênia", alpha3: "ARM", numeric: "051" },
  { alpha2: "AW", name: "Aruba", alpha3: "ABW", numeric: "533" },
  { alpha2: "AU", name: "Austrália", alpha3: "AUS", numeric: "036" },
  { alpha2: "AT", name: "Áustria", alpha3: "AUT", numeric: "040" },
  { alpha2: "AZ", name: "Azerbaijão", alpha3: "AZE", numeric: "031" },
  { alpha2: "BS", name: "Bahamas", alpha3: "BHS", numeric: "044" },
  { alpha2: "BH", name: "Bahrein", alpha3: "BHR", numeric: "048" },
  { alpha2: "BD", name: "Bangladesh", alpha3: "BGD", numeric: "050" },
  { alpha2: "BB", name: "Barbados", alpha3: "BRB", numeric: "052" },
  { alpha2: "BY", name: "Belarus", alpha3: "BLR", numeric: "112" },
  { alpha2: "BE", name: "Bélgica", alpha3: "BEL", numeric: "056" },
  { alpha2: "BZ", name: "Belize", alpha3: "BLZ", numeric: "084" },
  { alpha2: "BJ", name: "Benin", alpha3: "BEN", numeric: "204" },
  { alpha2: "BM", name: "Bermudas", alpha3: "BMU", numeric: "060" },
  { alpha2: "BT", name: "Butão", alpha3: "BTN", numeric: "064" },
  { alpha2: "BO", name: "Bolívia", alpha3: "BOL", numeric: "068" },
  {
    alpha2: "BQ",
    name: "Bonaire",
    alpha3: "BES",
    numeric: "535",
  },
  {
    alpha2: "BA",
    name: "Bósnia-Herzegóvina",
    alpha3: "BIH",
    numeric: "070",
  },
  { alpha2: "BW", name: "Botsuana", alpha3: "BWA", numeric: "072" },
  { alpha2: "BV", name: "Ilha Bouvet", alpha3: "BVD", numeric: "074" },
  { alpha2: "BR", name: "Brasil", alpha3: "BRA", numeric: "076" },
  {
    alpha2: "IO",
    name: "Terr. Britânico do Oceano Índico",
    alpha3: "IOT",
    numeric: "086",
  },
  { alpha2: "BN", name: "Brunei", alpha3: "BRN", numeric: "096" },
  { alpha2: "BG", name: "Bulgária", alpha3: "BGR", numeric: "100" },
  { alpha2: "BF", name: "Burkina Fasso", alpha3: "BFA", numeric: "854" },
  { alpha2: "BI", name: "Burundi", alpha3: "BDI", numeric: "108" },
  { alpha2: "KH", name: "Camboja", alpha3: "KHM", numeric: "116" },
  { alpha2: "CM", name: "Camarões", alpha3: "CMR", numeric: "120" },
  { alpha2: "CA", name: "Canadá", alpha3: "CAN", numeric: "124" },
  { alpha2: "CV", name: "Cabo Verde", alpha3: "CPV", numeric: "132" },
  { alpha2: "KY", name: "Ilhas Cayman", alpha3: "CYM", numeric: "136" },
  {
    alpha2: "CF",
    name: "República Centro-Africana",
    alpha3: "CAF",
    numeric: "140",
  },
  { alpha2: "TD", name: "Chade", alpha3: "TCD", numeric: "148" },
  { alpha2: "CL", name: "Chile", alpha3: "CHL", numeric: "152" },
  { alpha2: "CN", name: "China", alpha3: "CHN", numeric: "156" },
  { alpha2: "CX", name: "Ilha Natal", alpha3: "CXR", numeric: "162" },
  {
    alpha2: "CC",
    name: "Ilhas Cocos",
    alpha3: "CCK",
    numeric: "166",
  },
  { alpha2: "CO", name: "Colômbia", alpha3: "COL", numeric: "170" },
  { alpha2: "KM", name: "Comoros", alpha3: "COM", numeric: "174" },
  { alpha2: "CG", name: "Congo", alpha3: "COG", numeric: "178" },
  {
    alpha2: "CD",
    name: "D.R. Congo",
    alpha3: "COD",
    numeric: "180",
  },
  { alpha2: "CK", name: "Ilhas Cook", alpha3: "COK", numeric: "184" },
  { alpha2: "CR", name: "Costa Rica", alpha3: "CRI", numeric: "188" },
  { alpha2: "CI", name: "Costa do Marfim", alpha3: "CIV", numeric: "384" },
  { alpha2: "HR", name: "Croácia", alpha3: "HRV", numeric: "191" },
  { alpha2: "CU", name: "Cuba", alpha3: "CUB", numeric: "192" },
  { alpha2: "CW", name: "Curaçao", alpha3: "CUW", numeric: "531" },
  { alpha2: "CY", name: "Chipre", alpha3: "CYP", numeric: "196" },
  { alpha2: "CZ", name: "República Tcheca", alpha3: "CZE", numeric: "203" },
  { alpha2: "DK", name: "Dinamarca", alpha3: "DNK", numeric: "208" },
  { alpha2: "DJ", name: "Djibuti", alpha3: "DJI", numeric: "262" },
  { alpha2: "DM", name: "Dominica", alpha3: "DMA", numeric: "212" },
  { alpha2: "DO", name: "República Dominicana", alpha3: "DOM", numeric: "214" },
  { alpha2: "EC", name: "Equador", alpha3: "ECU", numeric: "218" },
  { alpha2: "EG", name: "Egito", alpha3: "EGY", numeric: "818" },
  { alpha2: "SV", name: "El Salvador", alpha3: "SLV", numeric: "222" },
  { alpha2: "GQ", name: "Guiné Equatorial", alpha3: "GNQ", numeric: "226" },
  { alpha2: "ER", name: "Eritréia", alpha3: "ERI", numeric: "232" },
  { alpha2: "EE", name: "Estônia", alpha3: "EST", numeric: "233" },
  { alpha2: "ET", name: "Etiópia", alpha3: "ETH", numeric: "231" },
  {
    alpha2: "FK",
    name: "Ilhas Falkland (Malvinas)",
    alpha3: "FLK",
    numeric: "238",
  },
  { alpha2: "FO", name: "Ilhas Faroes", alpha3: "FRO", numeric: "234" },
  { alpha2: "FJ", name: "Fiji", alpha3: "FJI", numeric: "242" },
  { alpha2: "FI", name: "Finlândia", alpha3: "FIN", numeric: "246" },
  { alpha2: "FR", name: "França", alpha3: "FRA", numeric: "250" },
  { alpha2: "GF", name: "Guiana Francesa", alpha3: "GUF", numeric: "254" },
  { alpha2: "PF", name: "Polinésia Francesa", alpha3: "PYF", numeric: "258" },
  {
    alpha2: "TF",
    name: "Territórios do Sul da França",
    alpha3: "ATF",
    numeric: "260",
  },
  { alpha2: "GA", name: "Gabão", alpha3: "GAB", numeric: "266" },
  { alpha2: "GM", name: "Gâmbia", alpha3: "GMB", numeric: "270" },
  { alpha2: "GE", name: "Geórgia", alpha3: "GEO", numeric: "268" },
  { alpha2: "DE", name: "Alemanha", alpha3: "DEU", numeric: "276" },
  { alpha2: "GH", name: "Gana", alpha3: "GHA", numeric: "288" },
  { alpha2: "GI", name: "Gibraltar", alpha3: "GIB", numeric: "292" },
  { alpha2: "GR", name: "Grécia", alpha3: "GRC", numeric: "300" },
  { alpha2: "GL", name: "Groelândia", alpha3: "GRL", numeric: "304" },
  { alpha2: "GD", name: "Granada", alpha3: "GRD", numeric: "308" },
  { alpha2: "GP", name: "Guadalupe", alpha3: "GLP", numeric: "312" },
  { alpha2: "GU", name: "Guam", alpha3: "GUM", numeric: "316" },
  { alpha2: "GT", name: "Guatemala", alpha3: "GTM", numeric: "320" },
  { alpha2: "GG", name: "Guernsey", alpha3: "GGY", numeric: "831" },
  { alpha2: "GN", name: "Guiné", alpha3: "GIN", numeric: "324" },
  { alpha2: "GW", name: "Guiné-Bissau", alpha3: "GNB", numeric: "624" },
  { alpha2: "GY", name: "Guiana", alpha3: "GUY", numeric: "328" },
  { alpha2: "HT", name: "Haiti", alpha3: "HTI", numeric: "332" },
  { alpha2: "HN", name: "Honduras", alpha3: "HND", numeric: "340" },
  { alpha2: "HK", name: "Hong Kong", alpha3: "HKG", numeric: "344" },
  { alpha2: "HU", name: "Hungria", alpha3: "HUN", numeric: "348" },
  { alpha2: "IS", name: "Islândia", alpha3: "ISL", numeric: "352" },
  { alpha2: "IN", name: "Índia", alpha3: "IND", numeric: "356" },
  { alpha2: "ID", name: "Indonésia", alpha3: "IDN", numeric: "360" },
  {
    alpha2: "IR",
    name: "Irã",
    alpha3: "IRN",
    numeric: "364",
  },
  { alpha2: "IQ", name: "Iraque", alpha3: "IRQ", numeric: "368" },
  { alpha2: "IE", name: "Irlanda", alpha3: "IRL", numeric: "372" },
  { alpha2: "IM", name: "Ilha do Homem", alpha3: "IMN", numeric: "833" },
  { alpha2: "IL", name: "Israel", alpha3: "ISR", numeric: "376" },
  { alpha2: "IT", name: "Itália", alpha3: "ITA", numeric: "380" },
  { alpha2: "JM", name: "Jamaica", alpha3: "JAM", numeric: "388" },
  { alpha2: "JP", name: "Japão", alpha3: "JPN", numeric: "392" },
  { alpha2: "JE", name: "Jersey", alpha3: "JEY", numeric: "832" },
  { alpha2: "JO", name: "Jordânia", alpha3: "JOR", numeric: "400" },
  { alpha2: "KZ", name: "Cazaquistão", alpha3: "KAZ", numeric: "398" },
  { alpha2: "KE", name: "Kênia", alpha3: "KEN", numeric: "404" },
  { alpha2: "KI", name: "Kiribati", alpha3: "KIR", numeric: "296" },
  { alpha2: "KR", name: "Coréia do Sul", alpha3: "KOR", numeric: "410" },
  { alpha2: "XK", name: "Kosovo", alpha3: "XKX", numeric: "900" },
  { alpha2: "KW", name: "Kuait", alpha3: "KWT", numeric: "414" },
  { alpha2: "KG", name: "Quirguistão", alpha3: "KGZ", numeric: "417" },
  { alpha2: "LV", name: "Letônia", alpha3: "LVA", numeric: "428" },
  { alpha2: "LB", name: "Líbano", alpha3: "LBN", numeric: "422" },
  { alpha2: "LS", name: "Lesoto", alpha3: "LSO", numeric: "426" },
  { alpha2: "LR", name: "Libéria", alpha3: "LBR", numeric: "430" },
  { alpha2: "LI", name: "Liechtenstein", alpha3: "LIE", numeric: "438" },
  { alpha2: "LT", name: "Lituânia", alpha3: "LTU", numeric: "440" },
  { alpha2: "LU", name: "Luxemburgo", alpha3: "LUX", numeric: "442" },
  { alpha2: "MO", name: "Macau", alpha3: "MAC", numeric: "446" },
  {
    alpha2: "MK",
    name: "Macedônia",
    alpha3: "MKD",
    numeric: "807",
  },
  { alpha2: "MG", name: "Madagascar", alpha3: "MDG", numeric: "450" },
  { alpha2: "MW", name: "Malaui", alpha3: "MWI", numeric: "454" },
  { alpha2: "MY", name: "Malásia", alpha3: "MYS", numeric: "458" },
  { alpha2: "MV", name: "Maldivas", alpha3: "MDV", numeric: "462" },
  { alpha2: "ML", name: "Mali", alpha3: "MLI", numeric: "466" },
  { alpha2: "MT", name: "Malta", alpha3: "MLT", numeric: "470" },
  { alpha2: "MH", name: "Ilhas Marshall", alpha3: "MHL", numeric: "584" },
  { alpha2: "MQ", name: "Martinica", alpha3: "MTQ", numeric: "474" },
  { alpha2: "MR", name: "Mauritânia", alpha3: "MRT", numeric: "478" },
  { alpha2: "MU", name: "Maurício", alpha3: "MUS", numeric: "480" },
  { alpha2: "YT", name: "Mayotte", alpha3: "MYT", numeric: "175" },
  { alpha2: "MX", name: "México", alpha3: "MEX", numeric: "484" },
  {
    alpha2: "FM",
    name: "Micronésia",
    alpha3: "FSM",
    numeric: "583",
  },
  { alpha2: "MD", name: "Moldova, Republic of", alpha3: "MDA", numeric: "498" },
  { alpha2: "MC", name: "Mônaco", alpha3: "MCO", numeric: "492" },
  { alpha2: "MN", name: "Mongólia", alpha3: "MNG", numeric: "496" },
  { alpha2: "ME", name: "Montenegro", alpha3: "MNE", numeric: "499" },
  { alpha2: "MS", name: "Montserrat", alpha3: "MSR", numeric: "500" },
  { alpha2: "MA", name: "Marrocos", alpha3: "MAR", numeric: "504" },
  { alpha2: "MZ", name: "Moçambique", alpha3: "MOZ", numeric: "508" },
  { alpha2: "MM", name: "Myamar", alpha3: "MMR", numeric: "104" },
  { alpha2: "NA", name: "Namíbia", alpha3: "NAM", numeric: "516" },
  { alpha2: "NR", name: "Nauru", alpha3: "NRU", numeric: "520" },
  { alpha2: "NP", name: "Nepal", alpha3: "NPL", numeric: "524" },
  { alpha2: "NL", name: "Holanda", alpha3: "NLD", numeric: "528" },
  { alpha2: "NC", name: "Nova Caledônia", alpha3: "NCL", numeric: "540" },
  { alpha2: "NZ", name: "Nova Zelândia", alpha3: "NZL", numeric: "554" },
  { alpha2: "NI", name: "Nicarágua", alpha3: "NIC", numeric: "558" },
  { alpha2: "NE", name: "Níger", alpha3: "NER", numeric: "562" },
  { alpha2: "NG", name: "Nigéria", alpha3: "NGA", numeric: "566" },
  { alpha2: "NU", name: "Niue", alpha3: "NIU", numeric: "570" },
  { alpha2: "NF", name: "Ilhas Norfolk", alpha3: "NFK", numeric: "574" },
  {
    alpha2: "MP",
    name: "Ilhas Marianas do Norte",
    alpha3: "MNP",
    numeric: "580",
  },
  { alpha2: "NO", name: "Noruega", alpha3: "NOR", numeric: "578" },
  { alpha2: "OM", name: "Omã", alpha3: "OMN", numeric: "512" },
  { alpha2: "PK", name: "Paquistão", alpha3: "PAK", numeric: "586" },
  { alpha2: "PW", name: "Palau", alpha3: "PLW", numeric: "585" },
  {
    alpha2: "PS",
    name: "Palestina/Gaza",
    alpha3: "PSE",
    numeric: "275",
  },
  { alpha2: "PA", name: "Panamá", alpha3: "PAN", numeric: "591" },
  { alpha2: "PG", name: "Papua-Nova Guiné", alpha3: "PNG", numeric: "598" },
  { alpha2: "PY", name: "Paraguai", alpha3: "PRY", numeric: "600" },
  { alpha2: "PE", name: "Peru", alpha3: "PER", numeric: "604" },
  { alpha2: "PH", name: "Filipinas", alpha3: "PHL", numeric: "608" },
  { alpha2: "PN", name: "Pitcairn", alpha3: "PCN", numeric: "612" },
  { alpha2: "PL", name: "Polônia", alpha3: "POL", numeric: "616" },
  { alpha2: "PT", name: "Portugal", alpha3: "PRT", numeric: "620" },
  { alpha2: "PR", name: "Porto Rico", alpha3: "PRI", numeric: "630" },
  { alpha2: "QA", name: "Qatar", alpha3: "QAT", numeric: "634" },
  { alpha2: "RE", name: "Ilhas Reunião", alpha3: "REU", numeric: "638" },
  { alpha2: "RO", name: "Romênia", alpha3: "ROU", numeric: "642" },
  { alpha2: "RO", name: "Romênia", alpha3: "ROM", numeric: "642" },
  { alpha2: "RU", name: "Federação Russa", alpha3: "RUS", numeric: "643" },
  { alpha2: "RW", name: "Ruanda", alpha3: "RWA", numeric: "646" },
  { alpha2: "BL", name: "São Bartolomeu", alpha3: "BLM", numeric: "652" },
  { alpha2: "SH", name: "Santa Helena", alpha3: "SHN", numeric: "654" },
  {
    alpha2: "KN",
    name: "São Cristóvão e Névis (Kitts)",
    alpha3: "KNA",
    numeric: "659",
  },
  { alpha2: "LC", name: "Santa Lúcia", alpha3: "LCA", numeric: "662" },
  {
    alpha2: "MF",
    name: "São Martim",
    alpha3: "MAF",
    numeric: "663",
  },
  {
    alpha2: "PM",
    name: "São Pedro e Miquelon",
    alpha3: "SPM",
    numeric: "666",
  },
  {
    alpha2: "VC",
    name: "São Vincente e Granadinas",
    alpha3: "VCT",
    numeric: "670",
  },
  { alpha2: "WS", name: "Samoa Ocidental", alpha3: "WSM", numeric: "882" },
  { alpha2: "SM", name: "San Marino", alpha3: "SMR", numeric: "674" },
  {
    alpha2: "ST",
    name: "São Tomé e Príncipe",
    alpha3: "STP",
    numeric: "678",
  },
  { alpha2: "SA", name: "Arábia Saudita", alpha3: "SAU", numeric: "682" },
  { alpha2: "SN", name: "Senegal", alpha3: "SEN", numeric: "686" },
  { alpha2: "RS", name: "Sérvia", alpha3: "SRB", numeric: "688" },
  { alpha2: "SC", name: "Ilhas Seychelles", alpha3: "SYC", numeric: "690" },
  { alpha2: "SL", name: "Serra Leoa", alpha3: "SLE", numeric: "694" },
  { alpha2: "SG", name: "Cingapura", alpha3: "SGP", numeric: "702" },
  { alpha2: "SX", name: "São Maarten", alpha3: "SXM", numeric: "534" },
  { alpha2: "SK", name: "Eslováquia", alpha3: "SVK", numeric: "703" },
  { alpha2: "SI", name: "Eslovênia", alpha3: "SVN", numeric: "705" },
  { alpha2: "SB", name: "Ilhas Solomão", alpha3: "SLB", numeric: "090" },
  { alpha2: "SO", name: "Somália", alpha3: "SOM", numeric: "706" },
  { alpha2: "ZA", name: "África do Sul", alpha3: "ZAF", numeric: "710" },
  { alpha2: "SS", name: "Sudão do Sul", alpha3: "SSD", numeric: "728" },
  { alpha2: "ES", name: "Espanha", alpha3: "ESP", numeric: "724" },
  { alpha2: "LK", name: "Sri Lanka", alpha3: "LKA", numeric: "144" },
  { alpha2: "SD", name: "Sudão", alpha3: "SDN", numeric: "729" },
  { alpha2: "SR", name: "Suriname", alpha3: "SUR", numeric: "740" },
  {
    alpha2: "SJ",
    name: "Ilhas Svalbard e Jan Mayen",
    alpha3: "SJM",
    numeric: "744",
  },
  { alpha2: "SZ", name: "Suazilânida", alpha3: "SWZ", numeric: "748" },
  { alpha2: "SE", name: "Suécia", alpha3: "SWE", numeric: "752" },
  { alpha2: "CH", name: "Suíça", alpha3: "CHE", numeric: "756" },
  { alpha2: "SY", name: "Síria", alpha3: "SYR", numeric: "760" },
  {
    alpha2: "TW",
    name: "Taiwan",
    alpha3: "TWN",
    numeric: "158",
  },
  { alpha2: "TJ", name: "Tajiquistão", alpha3: "TJK", numeric: "762" },
  {
    alpha2: "TZ",
    name: "Tanzânia",
    alpha3: "TZA",
    numeric: "834",
  },
  { alpha2: "TH", name: "Tailândia", alpha3: "THA", numeric: "764" },
  { alpha2: "TL", name: "Timor Leste", alpha3: "TLS", numeric: "626" },
  { alpha2: "TG", name: "Togo", alpha3: "TGO", numeric: "768" },
  { alpha2: "TK", name: "Ilhas Tokelau", alpha3: "TKL", numeric: "772" },
  { alpha2: "TO", name: "Tonga", alpha3: "TON", numeric: "776" },
  { alpha2: "TT", name: "Trinidade e Tobago", alpha3: "TTO", numeric: "780" },
  { alpha2: "TN", name: "Tunísia", alpha3: "TUN", numeric: "788" },
  { alpha2: "TR", name: "Turquia", alpha3: "TUR", numeric: "792" },
  { alpha2: "TM", name: "Turcomenistão", alpha3: "TKM", numeric: "795" },
  {
    alpha2: "TC",
    name: "Ilhas Turks e Caicos",
    alpha3: "TCA",
    numeric: "796",
  },
  { alpha2: "TV", name: "Tuvalu", alpha3: "TUV", numeric: "798" },
  { alpha2: "UG", name: "Uganda", alpha3: "UGA", numeric: "800" },
  { alpha2: "UA", name: "Ucrânia", alpha3: "UKR", numeric: "804" },
  {
    alpha2: "AE",
    name: "Emirados Árabes Unidos",
    alpha3: "ARE",
    numeric: "784",
  },
  { alpha2: "GB", name: "Reino Unido", alpha3: "GBR", numeric: "826" },
  { alpha2: "US", name: "Estados Unidos", alpha3: "USA", numeric: "840" },
  {
    alpha2: "UM",
    name: "Ilhas Menores dos EUA",
    alpha3: "UMI",
    numeric: "581",
  },
  { alpha2: "UY", name: "Uruguai", alpha3: "URY", numeric: "858" },
  { alpha2: "UZ", name: "Uzbequistão", alpha3: "UZB", numeric: "860" },
  { alpha2: "VU", name: "Vanuatu", alpha3: "VUT", numeric: "548" },
  { alpha2: "VE", name: "Venezuela", alpha3: "VEN", numeric: "862" },
  { alpha2: "VN", name: "Vietnã", alpha3: "VNM", numeric: "704" },
  {
    alpha2: "VG",
    name: "Ilhas Virgens (Inglaterra)",
    alpha3: "VGB",
    numeric: "092",
  },
  { alpha2: "VI", name: "Ilhas Virgens (EUA)", alpha3: "VIR", numeric: "850" },
  {
    alpha2: "WF",
    name: "Ilhas Wallis e Futuna",
    alpha3: "WLF",
    numeric: "876",
  },
  { alpha2: "EH", name: "Saara Ocidental", alpha3: "ESH", numeric: "732" },
  { alpha2: "YE", name: "Iêmen", alpha3: "YEM", numeric: "887" },
  { alpha2: "ZM", name: "Zâmbia", alpha3: "ZMB", numeric: "894" },
  { alpha2: "ZW", name: "Zimbábue", alpha3: "ZWE", numeric: "716" },
  { alpha2: "AX", name: "Ilhas Aland", alpha3: "ALA", numeric: "248" },
]

export function countryLookup(isoCountryCode) {
  if (!isoCountryCode) {
    return
  }

  const normalizedIsoCountryCode = isoCountryCode.toUpperCase()

  if (isoAlpha2Countries[normalizedIsoCountryCode]) {
    return isoAlpha2Countries[normalizedIsoCountryCode]
  } else {
    // try iso alpha 3
    const isoRecord = countries.find(
      (record) => record.alpha3 === normalizedIsoCountryCode
    )

    if (isoRecord) {
      return isoRecord.name
    }

    throw new Error("Invalid country code")
  }
}
